[package]
name = "lever_framework"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/lever_core", 
    "crates/lever_gen",
]

[dependencies]
lever_core = { path = "crates/lever_core" }
lever_gen = { path = "crates/lever_gen" }

